<?php
session_start();
/* require('vendor/setasign/fpdf/fpdf.php'); */
require 'table_structure.php';
//ini_set('memory_limit', '1G');

class PDF extends FPDF {

    public $barangay;
    public $AdminName;

    function Header() {
        // Add the image
        $this->Image('assets/images/dswd-logo.png', 10, 10, 30); // Adjust the x, y, and size parameters as needed
        $this->Image('assets/images/buenaLogo.png', 255, 10, 25);

        // Set font for the main title
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(0, 7, 'Department of Social Welfare and Development', 0, 1, 'C');
        
        // Set font for the location
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Buenavista, Agusan Del Norte. 8601 Philippines', 0, 1, 'C');

        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Admin Document Reports', 0, 1, 'C');
        $this->Ln(5);
        
        // Print the barangay name from the property
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 10, $this->barangay, 0, 1, 'C');
        $this->Ln(5);

        $this->SetFont('Arial', 'B', 10);
        // table header
        $this->Cell(51, 10, 'Name', 1);
        $this->Cell(45, 10, 'HHID', 1);
        $this->Cell(16, 10, 'GIS', 1);
        $this->Cell(26, 10, 'SWDI Result', 1);
        $this->Cell(16, 10, 'HAF', 1);
        $this->Cell(16, 10, 'SCSR', 1);
        $this->Cell(16, 10, 'CAR', 1);
        $this->Cell(16, 10, 'AER', 1);
        $this->Cell(31, 10, 'Progress Notes', 1);
        $this->Cell(16, 10, 'PSMS', 1);
        $this->Cell(31, 10, 'Referral Letters', 1);
        $this->Ln();
    }

    function Footer() {
       // Set the position to 15 mm from the bottom
       $this->SetY(-15);
       // Set font for the footer text
       $this->SetFont('Arial', 'I', 8);
       // Get the page width
       $pageWidth = $this->GetPageWidth();
       // Date on the left
       $date = date('F j, Y'); // Example date format
       $this->SetX(10); // Position from the left margin
       $this->Cell(0, 10, 'Date: ' . $date, 0, 0, 'L');
       // Page number in the center
       $this->SetX($pageWidth / 28); // Move to the center
       $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
       // Generated by on the right
       $this->SetX($pageWidth - 60); // Move to the right (adjust the 60 as needed for spacing)
       $this->Cell(0, 10, 'Generated by: ' . $this->AdminName, 0, 0, 'R');
    }

    function ChapterBody($data) {
        $this->SetFont('Arial', '', 10);

        foreach ($data as $row) {
            $this->Cell(51, 10, htmlspecialchars($row['fname'] . ' ' . $row['mname'] . ' ' . $row['lname']), 1);
            $this->Cell(45, 10, formathhid(htmlspecialchars($row['hhid'])), 1);

            $this->Cell(16, 10, $row['gis_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(26, 10, $row['swdi_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(16, 10, $row['haf_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(16, 10, $row['scsr_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(16, 10, $row['car_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(16, 10, $row['aer_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(31, 10, $row['pn_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(16, 10, $row['psms_img'] ? 'Yes' : 'No', 1, 0, 'C');
            $this->Cell(31, 10, $row['rl_img'] ? 'Yes' : 'No', 1, 0, 'C');

            $this->Ln();
        }
    }

}

// all years
class PDFYEAR extends PDF_MC_Table {

    public $barangayYear;
    public $AdminName;

    function Header() {
        // Add the image
        $this->Image('assets/images/dswd-logo.png', 10, 10, 30); // Adjust the x, y, and size parameters as needed
        $this->Image('assets/images/buenaLogo.png', 255, 10, 25);

        // Set font for the main title
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(0, 7, 'Department of Social Welfare and Development', 0, 1, 'C');
        
        // Set font for the location
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Buenavista, Agusan Del Norte. 8601 Philippines', 0, 1, 'C');

        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Admin Document Reports', 0, 1, 'C');
        $this->Ln(5);
        
        // Print the barangay name from the property
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 10, $this->barangayYear, 0, 1, 'C');
        $this->Ln(5);

        $this->SetFont('Arial', 'B', 10.5);

        // Define the column widths and alignments
        $this->SetWidths([48, 45, 16, 26, 16, 16, 16, 16, 31, 16, 31]);
        $this->SetAligns(['L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L']);

        // Print header row
        $this->Row([
            'Name',
            'HHID',
            'GIS',
            'SWDI Result',
            'HAF',
            'SCSR',
            'CAR',
            'AER',
            'Progress Notes',
            'PSMS',
            'Referral Letters'
        ]);
    }

    function Footer() {
        // Set the position to 15 mm from the bottom
        $this->SetY(-15);
        // Set font for the footer text
        $this->SetFont('Arial', 'I', 8);
        // Get the page width
        $pageWidth = $this->GetPageWidth();
        // Date on the left
        $date = date('F j, Y'); // Example date format
        $this->SetX(10); // Position from the left margin
        $this->Cell(0, 10, 'Date: ' . $date, 0, 0, 'L');
        // Page number in the center
        $this->SetX($pageWidth / 26); // Move to the center
        $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        // Generated by on the right
        $this->SetX($pageWidth - 60); // Move to the right (adjust the 60 as needed for spacing)
        $this->Cell(0, 10, 'Generated by: ' . $this->AdminName, 0, 0, 'R');
    }

    function ChapterBody($data) {
        $this->SetFont('Arial', '', 10.5);

        $this->SetAligns(['L', 'L', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C']);
        
        foreach ($data as $name => $details) {
            preg_match('/^(.*)\s\((\d+)\)$/', $name, $matches);
            $name = $matches[1] ?? 'N/A'; 
            $hhid = $matches[2] ?? 'N/A'; 

            // Prepare data for each row
            $row = [];
            $row[] = htmlspecialchars($name);
            $row[] = formathhid(htmlspecialchars($hhid));

            // Prepare GIS documents
            $gisDetails = '';
            if (!empty($details['gis'])) {
                foreach ($details['gis'] as $gis) {
                    $gisDetails .= $gis['gis_year'] . "\n";
                }
            }
            $row[] = trim($gisDetails);

            // Prepare SWDI Result documents
            $swdiDetails = '';
            if (!empty($details['swdi'])) {
                foreach ($details['swdi'] as $swdi) {
                    $swdiDetails .= $swdi['swdi_year'] . "\n";
                }
            }
            $row[] = trim($swdiDetails);

            // Prepare HAF documents
            $hafDetails = '';
            if (!empty($details['haf'])) {
                foreach ($details['haf'] as $haf) {
                    $hafDetails .= $haf['haf_year'] . "\n";
                }
            }
            $row[] = trim($hafDetails);

            // Prepare SCSR documents
            $scsrDetails = '';
            if (!empty($details['scsr'])) {
                foreach ($details['scsr'] as $scsr) {
                    $scsrDetails .= $scsr['scsr_year'] . "\n";
                }
            }
            $row[] = trim($scsrDetails);

            // Prepare CAR documents
            $carDetails = '';
            if (!empty($details['car'])) {
                foreach ($details['car'] as $car) {
                    $carDetails .= $car['car_year'] . "\n";
                }
            }
            $row[] = trim($carDetails);

            // Prepare AER documents
            $aerDetails = '';
            if (!empty($details['aer'])) {
                foreach ($details['aer'] as $aer) {
                    $aerDetails .= $aer['aer_year'] . "\n";
                }
            }
            $row[] = trim($aerDetails);

            // Prepare Progress Notes documents
            $pnDetails = '';
            if (!empty($details['pn'])) {
                foreach ($details['pn'] as $pn) {
                    $pnDetails .= $pn['pn_year'] . "\n";
                }
            }
            $row[] = trim($pnDetails);

            // Prepare PSMS documents
            $psmsDetails = '';
            if (!empty($details['psms'])) {
                foreach ($details['psms'] as $psms) {
                    $psmsDetails .= $psms['psms_year'] . "\n";
                }
            }
            $row[] = trim($psmsDetails);

            // Prepare Referral Letters documents
            $rlDetails = '';
            if (!empty($details['rl'])) {
                foreach ($details['rl'] as $rl) {
                    $rlDetails .= $rl['rl_year'] . "\n";
                }
            }
            $row[] = trim($rlDetails);

            // Add row to the table
            $this->Row($row);
        }
    }
}

if (isset($_GET['barangay']) && $_GET['year'] === 'All') {
    $barangayYear = $_GET['barangay'];

    require_once 'server/fetch_data/pdf_search_2.php';

    // Create PDF
    $pdf = new PDFYEAR();
    $pdf->barangayYear = $barangayYear;
    $pdf->AdminName = $_SESSION['fname'] . " " . $_SESSION['mname'] . " " . $_SESSION['lname'];
    $pdf->AddPage('L');

    // Ensure $organizedData is correctly populated with the data
    if (isset($organizedData[$barangayYear])) {
        $pdf->ChapterBody($organizedData[$barangayYear]);
    } else {
        $pdf->Cell(0, 10, 'No data available for the selected barangay.', 0, 1, 'C');
    }

} else if (isset($_GET['barangay']) && $_GET['year'] === date('Y')){
    $barangay = $_GET['barangay'];

    require_once 'server/fetch_data/pdf_search.php';

    // Create PDF
    $pdf = new PDF();
    $pdf->barangay = $barangay . ' - ' . date('Y');
    $pdf->AdminName = $_SESSION['fname'] . " " . $_SESSION['mname'] . " " . $_SESSION['lname'];
    $pdf->AddPage('L');

    // Ensure $barangayGroups is correctly populated with the data
    if (isset($barangayGroups[$barangay])) {
        $pdf->ChapterBody($barangayGroups[$barangay]);
    } else {
        $pdf->Cell(0, 10, 'No data available for the selected barangay.', 0, 1, 'C');
    }
}

// Output the PDF
$filename = 'Admin_Submitted_Data_Reports_' . date('Ymd_His') . '.pdf';
$pdf->Output($filename, 'I');

?>
