<?php
session_start();
/* require('vendor/setasign/fpdf/fpdf.php'); */
require 'table_structure.php';
//ini_set('memory_limit', '1G');

function formathhid($hhid) {
    // Assuming $hhid is a string with 18 characters
    return substr($hhid, 0, 9) . '-' . substr($hhid, 9, 4) . '-' . substr($hhid, 13);
}

function formatid($id) {
    // Assuming $id is a string with 16 characters
    return substr($id, 0, 4) . '-' . substr($id, 4, 4) . '-' . substr($id, 8, 4) . '-' . substr($id, 12);
}

class PDF extends FPDF {

    public $barangay;
    public $AdminName;

    function Header() {
        // Add the image
        $this->Image('assets/images/dswd-logo.png', 10, 10, 30); // Adjust the x, y, and size parameters as needed
        $this->Image('assets/images/buenaLogo.png', 170, 10, 25);

        // Set font for the main title
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(0, 7, 'Department of Social Welfare and Development', 0, 1, 'C');
        
        // Set font for the location
        $this->SetFont('Arial', 'B', 12.5);
        $this->Cell(0, 7, 'Buenavista, Agusan Del Norte. 8601 Philippines', 0, 1, 'C');

        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Exited Beneficiary Reports', 0, 1, 'C');
        $this->Ln(5);
        
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 10, $this->barangay, 0, 1, 'C');
        $this->Ln();

        $this->SetFont('Arial', 'B', 10);
        $this->Cell(46, 10, 'Name', 1);
        $this->Cell(41, 10, 'HHID', 1);
        $this->Cell(25, 10, 'Number', 1);
        $this->Cell(11, 10, 'Set', 1);
        $this->Cell(14, 10, 'Purok', 1);
        $this->Cell(20, 10, 'Status', 1);
        $this->Cell(38, 10, 'Phylsis ID', 1);
        $this->Ln();
    }

    function Footer() {
        // Set the position to 15 mm from the bottom
        $this->SetY(-15);
        // Set font for the footer text
        $this->SetFont('Arial', 'I', 8);
        // Get the page width
        $pageWidth = $this->GetPageWidth();
        // Date on the left
        $date = date('F j, Y'); // Example date format
        $this->SetX(10); // Position from the left margin
        $this->Cell(0, 10, 'Date: ' . $date, 0, 0, 'L');
        // Page number in the center
        $this->SetX($pageWidth / 22); // Move to the center
        $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        // Generated by on the right
        $this->SetX($pageWidth - 60); // Move to the right (adjust the 60 as needed for spacing)
        $this->Cell(0, 10, 'Generated by: ' . $this->AdminName, 0, 0, 'R');
    }

    function ChapterBody($data) {
        $this->SetFont('Arial', '', 10);

        // Ensure $data is an array
        if (is_array($data)) {
            foreach ($data as $user) {
                // Ensure each $user is an array
                if (is_array($user)) {
                    $count_18_or_older = (int) $user['count_18_or_older'];
                    $total_Oo = (int) $user['total_Oo'];
                    $isComplete = $user['status'];
                    $status = ($isComplete === 'completed') ? $isComplete : $count_18_or_older . '/' . $total_Oo;

                    $this->Cell(46, 10, $user['fname'] . ' ' . $user['mname'] . ' ' . $user['lname'], 1);
                    $this->Cell(41, 10, formathhid($user['hhid']), 1);
                    $this->Cell(25, 10, $user['phone_number'], 1);
                    $this->Cell(11, 10, $user['user_set'], 1);
                    $this->Cell(14, 10, $user['purok'], 1);
                    $this->Cell(20, 10, $status, 1);
                    $this->Cell(38, 10, formatid($user['phylsis_id']), 1);
                    $this->Ln();
                    // Prepare the row data
                    /* $rowData = [
                        htmlspecialchars($user['fname'] . ' ' . $user['mname'] . ' ' . $user['lname']),
                        formathhid($user['hhid']),
                        htmlspecialchars($user['phone_number']),
                        htmlspecialchars($user['user_set']),
                        htmlspecialchars($user['purok']),
                        htmlspecialchars($status),
                        formatid($user['phylsis_id'])
                    ];

                    // Add a row with multi-line text handling
                    $this->Row($rowData); */
                } else {
                    // Handle unexpected data format
                    $this->Cell(0, 10, 'Unexpected data format.', 1, 1, 'C');
                }
            }
        } else {
            // Handle case where $data is not an array
            $this->Cell(0, 10, 'No data available or incorrect format.', 1, 1, 'C');
        }
    }
}

if (isset($_GET['barangay'])) {
    $barangay = $_GET['barangay'];
    
    require_once 'server/fetch_data/pdf_comsearch.php';

    // Create PDF
    $pdf = new PDF();
    $pdf->barangay = $barangay;
    $pdf->AdminName = $_SESSION['fname'] . " " . $_SESSION['mname'] . " " . $_SESSION['lname'];
    $pdf->AddPage();

    // Ensure $barangayGroups is correctly populated with the data
    if (isset($barangayGroups[$barangay])) {
        $pdf->ChapterBody($barangayGroups[$barangay]);
    } else {
        $pdf->Cell(0, 10, 'No data available for the selected barangay.', 0, 1, 'C');
    }

}

// Output the PDF
$filename = 'Exited_4ps_Reports_' . date('Ymd_His') . '.pdf';
$pdf->Output($filename, 'I');

?>
