<?php
session_start();
require 'vendor/autoload.php'; // This includes all Composer-installed libraries
require 'table_structure.php';
//ini_set('memory_limit', '1G');

use setasign\Fpdi\Fpdi;

class PDF extends PDF_MC_Table
{
    // Define a public property for barangay
    public $barangay;
    public $AdminName;

    // Add a header
    function Header()
    {
        // Add the image
        $this->Image('assets/images/dswd-logo.png', 10, 10, 30); // Adjust the x, y, and size parameters as needed
        $this->Image('assets/images/buenaLogo.png', 170, 10, 25);

        // Set font for the main title
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(0, 7, 'Department of Social Welfare and Development', 0, 1, 'C');
        
        // Set font for the location
        $this->SetFont('Arial', 'B', 12.5);
        $this->Cell(0, 7, 'Buenavista, Agusan Del Norte. 8601 Philippines', 0, 1, 'C');

        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Beneficiary Document Reports', 0, 1, 'C');
        $this->Ln(5);
        
        // Print the barangay name from the property
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 10, $this->barangay, 0, 1, 'C');
        $this->Ln(5);
    }

    function Body($data, $col1Width, $col2Width, $col3Width) {
        // Add a page
        $this->AddPage();
        
        // Set the font for the document type header
        $this->SetFont('Arial', 'B', 12);
        
        // Check data if set
        if (isset($data)) {
            foreach ($data as $docType => $people) {
                // Document Type Header
                $this->SetFont('Arial', 'B', 12);
                $this->Cell(0, 10, strtoupper($docType), 1, 1, 'C');
                /* $this->Ln(5);  */// Adjust spacing here

                // Set column widths and alignments
                $this->SetWidths([$col1Width, $col2Width, $col3Width]);
                $this->SetAligns(['L', 'L', 'L']);

                // Table Header
                $this->SetFont('Arial', 'B', 11);
                $header = ['Username', 'Document Info', 'Document Year'];
                $this->Row($header);
                
                // Set font for table rows
                $this->SetFont('Arial', '', 11);

                foreach ($people as $name => $records) {
                    // Initialize row data with the username
                    $docInfos = [];
                    $years = [];
                    
                    // Prepare document info and years for the current username
                    foreach ($records as $record) {
                        // Document Info
                        $docInfo = $record['name'];
                        if (!empty($record['family_role'])) {
                            $docInfo .= ' (' . $record['family_role'] . ')';
                        }
                        $docInfos[] = $docInfo;
                        
                        // Document Year
                        $years[] = $record['upload_date'];
                    }
                    
                    // Concatenate document info and years
                    $allDocInfo = implode("\n", $docInfos);
                    $allYears = implode("\n", $years);

                    // Prepare the row data
                    $row = [$name, $allDocInfo, $allYears];
                    
                    // Add the row to the table
                    $this->Row($row);
                    
                    // Only add extra space between different users, not between records of the same user
                    /* $this->Ln(2);  */// Adjust spacing as needed
                }

                $this->Ln(12); // Space between different document types
            }
        }
    }

    // Add a footer
    function Footer()
    {
        // Set the position to 15 mm from the bottom
        $this->SetY(-15);
        // Set font for the footer text
        $this->SetFont('Arial', 'I', 8);
        // Get the page width
        $pageWidth = $this->GetPageWidth();
        // Date on the left
        $date = date('F j, Y'); // Example date format
        $this->SetX(10); // Position from the left margin
        $this->Cell(0, 10, 'Date: ' . $date, 0, 0, 'L');
        // Page number in the center
        $this->SetX($pageWidth / 22); // Move to the center
        $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        // Generated by on the right
        $this->SetX($pageWidth - 60); // Move to the right (adjust the 60 as needed for spacing)
        $this->Cell(0, 10, 'Generated by: ' . $this->AdminName, 0, 0, 'R');
    }
}


// Create PDF
$pdf = new PDF();
$pdf->AdminName = $_SESSION['fname'] . " " . $_SESSION['mname'] . " " . $_SESSION['lname'];
$col1Width = 60; // Username column width
$col2Width = 95; // Document Info column width
$col3Width = 35; // Document Year column width


if ($_SESSION['ryear'] != null && $_SESSION['rbrgy'] != null  && !isset($_GET['table'])) {
    $year = $_SESSION['ryear'];
    $barangay = $_SESSION['rbrgy'];
    // all documents and specific year
    require_once 'server/fetch_data/print_year.php';
    $pdf->barangay = $barangay . ' - ' . $year;
    $pdf->Body($data[$barangay] ?? null, $col1Width, $col2Width, $col3Width);

} else if ($_SESSION['ryear'] != null && $_SESSION['rbrgy'] != null && isset($_GET['table']) && isset($_GET['barangay'])) {
    $year = $_SESSION['ryear'];
    $table = $_GET['table'];
    $barangay = $_GET['barangay'];
    // 1 document and specific year
    require_once 'server/fetch_data/print_stable.php';
    $pdf->barangay = $barangay . ' - ' . $year;
    $pdf->Body($data, $col1Width, $col2Width, $col3Width);

} else if ($_SESSION['ryear'] == null && $_SESSION['rbrgy'] == null && isset($_GET['table']) && isset($_GET['barangay'])){
    $table = $_GET['table'];
    $barangay = $_GET['barangay'];
    // all year but 1 document
    require_once 'server/fetch_data/print_atable.php';
    $pdf->barangay = $barangay;
    $pdf->Body($data, $col1Width, $col2Width, $col3Width);

} else if($_SESSION['ryear'] == null && $_SESSION['rbrgy'] == null && !isset($_GET['table'])) {
    $barangay = $_GET['barangay'];
    // all documents and all years
    require_once 'server/fetch_data/print_brgy.php';
    $pdf->barangay = $barangay;
    $pdf->Body($data[$barangay] ?? null, $col1Width, $col2Width, $col3Width);
}


// Output the PDF
$filename = 'Document_Reports_' . date('Ymd_His') . '.pdf';
$pdf->Output($filename, 'I');


/* $pdf->Cell($width, $height, $text, $border, $ln, $align, $fill, $link); */

?>
