<?php
session_start();
require 'vendor/autoload.php'; // This includes all Composer-installed libraries
require 'table_structure.php'; // Include the custom table structure class
//ini_set('memory_limit', '1G');

// Define the PDF class with barangay property
class PDF extends PDF_MC_Table
{
    // Define a public property for barangay
    public $barangay;
    public $AdminName;

    // Add a header
    function Header()
    {
        // Add the image
        $this->Image('assets/images/dswd-logo.png', 10, 10, 30); // Adjust the x, y, and size parameters as needed
        $this->Image('assets/images/buenaLogo.png', 255, 10, 25);
        // Set font for the main title
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(0, 7, 'Department of Social Welfare and Development', 0, 1, 'C');
        // Set font for the location
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Buenavista, Agusan Del Norte. 8601 Philippines', 0, 1, 'C');
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 7, 'Non Compliance Data Report', 0, 1, 'C');
        $this->Ln(5);
        // Print the barangay name from the property
        $this->Cell(0, 10, $this->barangay, 0, 1, 'C');
        $this->Ln(10);

        $this->SetFont('Arial', 'B', 12);
        // Define column headers and widths
        $header = ['Name', 'HHID', 'Number', 'Set', 'Purok', 'Missing Data', 'Present Data'];
        $widths = [47, 48, 31, 17, 17, 60, 60];
        // Set column headers
        $this->SetWidths($widths);
        $this->SetAligns(['L', 'L', 'L', 'L', 'L', 'L', 'L']); // Alignments for each column
        $this->Row($header);
    }

    // Add a footer
    function Footer()
    {
        // Set the position to 15 mm from the bottom
       $this->SetY(-15);
       // Set font for the footer text
       $this->SetFont('Arial', 'I', 8);
       // Get the page width
       $pageWidth = $this->GetPageWidth();
       // Date on the left
       $date = date('F j, Y'); // Example date format
       $this->SetX(10); // Position from the left margin
       $this->Cell(0, 10, 'Date: ' . $date, 0, 0, 'L');
       // Page number in the center
       $this->SetX($pageWidth / 28); // Move to the center
       $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
       // Generated by on the right
       $this->SetX($pageWidth - 60); // Move to the right (adjust the 60 as needed for spacing)
       $this->Cell(0, 10, 'Generated by: ' . $this->AdminName, 0, 0, 'R');
    }
}

if (isset($_GET['barangay'])) {
    $barangay = $_GET['barangay'];

    // Start output buffering
   /*  ob_start(); */
    
    require_once 'server/fetch_data/pdf_ncsearch.php';

    // Instantiate PDF object and set barangay property
    $pdf = new PDF();
    $pdf->barangay = $barangay;
    $pdf->AdminName = $_SESSION['fname'] . " " . $_SESSION['mname'] . " " . $_SESSION['lname'];
    $pdf->AddPage('L');
    // Set font for data
    $pdf->SetFont('Arial', '', 12);

    foreach ($barangayGroups as $barangay => $users) {
        foreach ($users as $nameKey => $user) {
            list($name, $hhid) = explode('(', str_replace(')', '', $nameKey));
            $name = trim($name);
            $hhid = trim($hhid);

            // Prepare Missing Data and Present Data
            $no_data = is_array($user['no_data']) ? $user['no_data'] : [$user['no_data']];
            $has_data = is_array($user['has_data']) ? $user['has_data'] : [$user['has_data']];

            // Find the maximum number of rows required for Missing Data and Present Data
            $max_lines = max(count($no_data), count($has_data));

            for ($i = 0; $i < $max_lines; $i++) {
                $missing_data_item = isset($no_data[$i]) ? $no_data[$i] : '';
                $present_data_item = isset($has_data[$i]) ? $has_data[$i] : '';

                $pdf->Row([
                    $i === 0 ? $name : '', // Only display Name in the first row
                    $i === 0 ? formathhid($hhid) : '', // Only display HHID in the first row
                    $i === 0 ? $user['phone_number'] : '', // Only display Number in the first row
                    $i === 0 ? $user['user_set'] : '', // Only display Set in the first row
                    $i === 0 ? $user['purok'] : '', // Only display Purok in the first row
                    $missing_data_item, // Display Missing Data item
                    $present_data_item, // Display Present Data item
                ]);
            }
        }
    }

    // Flush the output buffer
   /*  ob_end_clean(); */
}
    // Define the file name
    $filename = 'Non_Compliance_Report_' . date('Ymd_His') . '.pdf';
    $pdf->Output($filename, 'I');
?>
